spring:
  application:
    name: deckbuilder
  profiles:
    active: openai # change to ollama for local testing free of charge

scryfall:
  base-url: https://api.scryfall.com

rag:
  rules-pdf-path: classpath:mtg-rules.pdf
  scryfall-syntax-path: classpath:scryfall-syntax.html
  max-results: 5
  min-score: 0.6
  chunk-size: 600
  chunk-overlap: 100
